Add ActionOnSave
ragurney/spotless-intellij-gradle pull request #33
Opened 2022-05-12 20:54 UTC by oraum

* add configuration to save whether action on save is enabled
* add actiononsave triggered on save of documents
* add infoprovider to show option in settings

[Heavily inspired by Jetbrains prettierJS plugin](https://github.com/JetBrains/intellij-plugins/tree/master/prettierJS)

resolves #8

2022-05-13 18:43 UTC, ragurney requested changes
Great work @oraum, thanks so much for the PR! I have a couple of nit-pick comments, and also we will need to bump the [plugin version](https://intellij-support.jetbrains.com/hc/en-us/community/posts/5552691613330-Running-Multiple-Reformat-Gradle-Tasks-Gives-Error) in this PR as well. 

The main blocker for this is that during manual testing I found it doesn't handle processing multiple files on save. It only formats the first file that is open, but errors out on the second. 
See [this](http://recordit.co/2oOgrTRGZO) for repro steps. 

I haven't had the chance to dig into this too much, but made a post [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/5552691613330-Running-Multiple-Reformat-Gradle-Tasks-Gives-Error) so hopefully we'll get an answer there on how to resolve this.

2022-05-13 22:50 UTC, oraum commented on src/main/java/com/github/ragurney/spotless/actions/SpotlessActionOnSave.java
> +            var file = PsiDocumentManager.getInstance(project).getPsiFile(document);
yeah the customer I currently work for prefers var so used it without thinking about it - anyways changed it

2022-05-13 22:51 UTC, oraum commented on src/main/java/com/github/ragurney/spotless/actions/SpotlessActionOnSave.java
> +            if (file == null) {
I tried to align the style to your ReformatCodeAction which is also using a explicit null check, but changed it.

2022-05-16 14:24 UTC, ragurney commented on src/main/java/com/github/ragurney/spotless/actions/SpotlessActionOnSave.java
> +            if (file == null) {
Ah yeah, sorry that's probably an artifact from me copying a lot of library code from intellij -- just trying to retroactively fix that enforcing a more preferred style. I'll go back and fix that code so others don't copy it. Thanks!

2022-05-16 14:28 UTC, ragurney reviewed
Changes look good @oraum, thanks a lot! 

I think the only blocker at this point is the resolution to the issue I mentioned with saving multiple files in [this comment](https://github.com/ragurney/spotless-intellij-gradle/pull/33#pullrequestreview-972558179).

I've asked IntelliJ what the proper fix for this is [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/5552691613330-Running-Multiple-Reformat-Gradle-Tasks-Gives-Error?page=1#community_comment_5586665749522), and hopefully we'll get an answer soon! It looks like they're saying to use the external formatter hook, but that would be a completely separate project as far as I understand it.

2024-04-17 07:35 UTC, pri-me commented
Hey guys, thanks for the work so far :) What is the status of this PR, looks "abandoned"?
I think, the ability to format on save the current file only is already quite useful because this is the main use case for this Action on Save anyway. For formatting several files/the whole project one can rely on Gradle (making spotlessApply part of the build chain and/or using a pre-commit hook). The main benefit of the Action on Save for me is being able to write stuff without paying attention to format and then it's tidied up during a thinking pause, thus keeping the code I am working on _readable_ :)
What is missing in the PR besides the conflicts? Maybe I could finish it.

2024-05-31 20:52 UTC, ErtugrulSener commented
> I think this is blocked until either [diffplug/spotless#791](https://github.com/diffplug/spotless/issues/791) is implemented and merged or we change this PR to only support format on save for the **current file only** due to the lack of gradle support to run multiple builds in parallel.

Hey. Could we just re-label this MR and ruf spotless for the currently opened file? This would already solve a lot.

2024-09-27 02:45 UTC, fokkoru commented
Any updates on this?

2026-08-20 22:08 UTC, closed without merging